[package]
name = "matsuo"
version = "0.1.0"
authors = ["l3ops <github@leops.me>"]

[dependencies]
gl = "0.6.2"
libc = "0.2.23"
glutin = "0.8.1"
rand = "0.3.15"
rayon = "0.7.1"
bincode = "0.8.0"
serde = "1.0.8"
serde_derive = "1.0.8"
docopt = "0.8.0"
